color: null
fieldLayouts:
  fd4264dd-eea1-429b-9a6c-0fa4bb3ff739:
    tabs:
      -
        elementCondition: null
        elements:
          -
            content: 'Bonjour {{ name }}, '
            dateAdded: '2025-12-09T13:04:26+00:00'
            displayInPane: true
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\SiteConditionRule
                  operator: in
                  uid: 25c0d146-ce0f-450c-a388-ede9581d575a
                  values:
                    - d74da9d4-3821-46f5-8cf4-f7c4d12c04df # Ledensysteem fr
              elementType: craft\elements\Entry
              fieldContext: global
            type: craft\fieldlayoutelements\Markdown
            uid: 7ca3127c-56aa-447c-9c8f-840253b805b0
            userCondition: null
            width: 100
          -
            content: 'Hi {{ naam }},'
            dateAdded: '2025-12-09T13:02:51+00:00'
            displayInPane: true
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\SiteConditionRule
                  operator: in
                  uid: dcfdc389-e9b6-4462-937c-a79e5a2199ae
                  values:
                    - 359a39c5-8655-460f-a1b4-0c097ea0edb2 # Ledensysteem
                    - dad48958-bcb3-4253-9f7e-868f67fa27b0 # Ledensysteem en
              elementType: craft\elements\Entry
              fieldContext: global
            type: craft\fieldlayoutelements\Markdown
            uid: 49195e01-e2e2-40c0-875d-c51d1b883a24
            userCondition: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-12-09T11:17:24+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2db3ae8c-8cbd-451b-ad12-4d713af5361a
            userCondition: null
            warning: 'Zal niets aanpassen in de mailing. Vraag het aan een developer om dit aan te passen.'
            width: 100
          -
            dateAdded: '2025-12-09T11:24:11+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8bcc63cf-9af7-4534-9702-b0378527d880 # Mailing
            handle: null
            includeInCards: false
            instructions: 'Eerste deel van mail indien er een knop tussen zit. Zo niet is dit het enige deel. '
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50f6bc1d-65fa-4928-a9d1-599bdcfad71b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-09T12:18:42+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aa21d2ca-e34c-4497-a6fa-49b5a7cc7f58 # Title
            handle: null
            includeInCards: false
            instructions: 'Enkel van toepassing wanneer er een knop is tussen de tekst.'
            label: 'Tekst voor in de knop'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7baf3004-ee4f-49dc-83db-ba66e94a17eb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-09T12:17:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8bcc63cf-9af7-4534-9702-b0378527d880 # Mailing
            handle: mailing2
            includeInCards: false
            instructions: 'Tweede deel van mail indien er een knop tussen zit. Zo niet wordt deze niet getoond. '
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 626c3713-e124-47fb-bf59-596f4359b41f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cbd465ee-1639-49c5-9293-dfd07f7dc544
        userCondition: null
handle: mailContent
hasTitleField: true
icon: envelope
name: 'Mail content'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
