defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 22f01f7b-1f35-49ff-b066-aab90e321e96 # Mail content
handle: mailings
maxAuthors: 1
name: Mailings
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  359a39c5-8655-460f-a1b4-0c097ea0edb2: # Ledensysteem
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  d74da9d4-3821-46f5-8cf4-f7c4d12c04df: # Ledensysteem fr
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  dad48958-bcb3-4253-9f7e-868f67fa27b0: # Ledensysteem en
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
